name: Create PR from PKMer Forum Post

on:
  repository_dispatch:
    types: [PKMer_forum_post]

jobs:
  commit-to-main:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        
    - name: Setup Git
      run: |
        git config --global user.name "pkmer Bot"
        git config --global user.email "pkmer.cn"
    - name: 1. Prepare file details and check for updates
      id: prepare_file
      env:
        POST_TITLE: ${{ github.event.client_payload.title }}
        TOPIC_ID: ${{ github.event.client_payload.topic_id }}
      run: |
        CLEAN_TITLE=$(echo "$POST_TITLE" | iconv -t ascii//TRANSLIT | sed -r 's/[^a-zA-Z0-9]+/-/g' | sed -r 's/^-+\|-+$//g' | tr '[:upper:]' '[:lower:]')
        FILENAME="${TOPIC_ID}-${CLEAN_TITLE}.md"
        FILEPATH="PKMer论坛/${FILENAME}"
        
        echo "filepath=${FILEPATH}" >> $GITHUB_OUTPUT
        if [ -f "$FILEPATH" ]; then
          echo "is_update=true" >> $GITHUB_OUTPUT
        else
          echo "is_update=false" >> $GITHUB_OUTPUT
        fi
    - name: Create content from  PKMer Forum post
      id: create_content
      env:
        FORUM_BASE_URL: "https://forum.pkmer.net"
        POST_AUTHOR: ${{ github.event.client_payload.author }}
        POST_TITLE: ${{ github.event.client_payload.title }}
        POST_TAGS_JSON: ${{ toJSON(github.event.client_payload.tags) }}
        POST_TIMESTAMP: ${{ github.event.client_payload.timestamp }}
        POST_SOURCE_URL: ${{ github.event.client_payload.source_url }}
        POST_RAW_CONTENT: ${{ github.event.client_payload.raw }}
      run: |
        # 创建文件路径和内容
        POST_ID="${{ github.event.client_payload.post_id }}"
        TOPIC_ID="${{ github.event.client_payload.topic_id }}"
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        
        # 清理标题以用作文件名的一部分，更友好
        CLEAN_TITLE=$(echo "$POST_TITLE" | tr -d '[:punct:]' | tr ' ' '-')
        FILENAME="${TOPIC_ID}-${CLEAN_TITLE}.md"
        FULL_FORUM_URL="$POST_SOURCE_URL"
        if [[ ! "$POST_SOURCE_URL" == http* ]]; then
          FULL_FORUM_URL="${FORUM_BASE_URL}${POST_SOURCE_URL}"
        fi
        # 标签数组转字符串
        TAGS_STRING=$(echo "$POST_TAGS_JSON" | jq -r 'map(select(. != "精华")) | join(", ")')
        # 设置文件路径（可以根据需要修改）
        FILEPATH="PKMer论坛/${FILENAME}"
        
        # 创建目录
        mkdir -p $(dirname "$FILEPATH")
        
        # 创建 Markdown 文件内容
        cat > "$FILEPATH" << EOF
        ---
        uid: ${POST_ID}
        title: ${POST_TITLE}
        tags: [${TAGS_STRING}]
        description: ${POST_TITLE}
        author: ${POST_AUTHOR}
        type: other
        draft: false
        editable: false
        modified: ${POST_TIMESTAMP}
        forum_url: ${FULL_FORUM_URL}
        ---
        
        # ${POST_TITLE}
        
        > [!INFO] 本文档由 PKMer 论坛导入  
        > - 作者: ${POST_AUTHOR}
        > - 原始链接: [${POST_TITLE}](${FULL_FORUM_URL})
        
        ---
        
        ${POST_RAW_CONTENT}
        
        EOF
        
        echo "filepath=$FILEPATH" >> $GITHUB_OUTPUT
        echo "filename=$FILENAME" >> $GITHUB_OUTPUT
        
    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v5
    #   with:
    #     token: ${{ secrets.PAT_TOKEN }}
    #     commit-message: |
    #       添加 PKMer论坛 帖子: ${{ github.event.client_payload.title }}
          
    #       - Post ID: ${{ github.event.client_payload.post_id }}
    #       - Author: ${{ github.event.client_payload.author  }}
    #       - Source: https://forum.pkmer.net${{ github.event.client_payload.source_url }}
    #     branch: forum-post-${{ github.event.client_payload.post_id }}
    #     delete-branch: true
    #     title: |
    #       ${{ github.event.client_payload.title }}
    #     body: |
    #       ## 📝 PKMer论坛 帖子导入
          
    #       本 PR 自动从  PKMer 论坛导入帖子内容。
          
    #       ### 帖子信息
    #       - **标题**: ${{ github.event.client_payload.title }}
    #       - **作者**: @${{ github.event.client_payload.author }}
    #       - **帖子 ID**: ${{ github.event.client_payload.post_id }}
    #       - **原始链接**: https://forum.pkmer.net${{ github.event.client_payload.source_url }}
          
    #       ### 文件路径
    #       - 📄 `${{ steps.create_content.outputs.filepath }}`
          
          
      
    #     labels: |
    #       auto-generated
    #       forum-post
    - name: 3. Commit and Push to main branch
      run: |
        # 把新创建或修改的文件添加到暂存区
        git add '${{ steps.prepare_file.outputs.filepath }}'
        
        # 检查是否有文件变更。如果没有变更（比如重复触发），就退出
        if git diff --staged --quiet; then
          echo "✅ No changes to commit. Working tree clean."
          exit 0
        fi
        # 根据是更新还是新建，生成不同的 commit message
        COMMIT_MESSAGE="${{ steps.prepare_file.outputs.is_update == 'true' && 'docs(forum): 更新帖子' || 'docs(forum): 添加新帖' }} L${{ github.event.client_payload.topic_id }}
        - 标题: ${{ github.event.client_payload.title }}"
        # 执行提交
        git commit -m "$COMMIT_MESSAGE"
        
        # 推送到远程 main 分支
        echo "🚀 Pushing changes to main branch..."
        git push origin main       

